export const browserCoreExamples = [
  "wildvine browser status",
  "wildvine browser start",
  "wildvine browser stop",
  "wildvine browser tabs",
  "wildvine browser open https://example.com",
  "wildvine browser focus abcd1234",
  "wildvine browser close abcd1234",
  "wildvine browser screenshot",
  "wildvine browser screenshot --full-page",
  "wildvine browser screenshot --ref 12",
  "wildvine browser snapshot",
  "wildvine browser snapshot --format aria --limit 200",
  "wildvine browser snapshot --efficient",
  "wildvine browser snapshot --labels",
];

export const browserActionExamples = [
  "wildvine browser navigate https://example.com",
  "wildvine browser resize 1280 720",
  "wildvine browser click 12 --double",
  'wildvine browser type 23 "hello" --submit',
  "wildvine browser press Enter",
  "wildvine browser hover 44",
  "wildvine browser drag 10 11",
  "wildvine browser select 9 OptionA OptionB",
  "wildvine browser upload /tmp/wildvine/uploads/file.pdf",
  'wildvine browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "wildvine browser dialog --accept",
  'wildvine browser wait --text "Done"',
  "wildvine browser evaluate --fn '(el) => el.textContent' --ref 7",
  "wildvine browser console --level error",
  "wildvine browser pdf",
];
